version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    rust: "1.96"

  apt_packages:
    - cmake
    - clang
    - pkg-config
    - libssl-dev
    - build-essential
    - libc6-dev
    - libclang-dev
    - llvm

  commands:
    - mkdir -p _readthedocs/html/

    # Generate .env file
    - |
      cat << 'EOF' > .env
      POLAR_API_KEY="key"
      URUKY_ID="id"
      RESULTI_API_KEY="key"
      URUKY_API_KEY="key"
      GOOGLE_API_KEY="key"
      GOOGLE_CX_KEY="key"
      BB2_URL="http://localhost"
      BB2_API_KEY="key"
      BRAVE_API_KEY="key"
      YADORE_API_KEY="key"
      UNSPLASH_API_KEY="key"
      FANART_API_KEY="key"
      NEWS_API_KEY="key"
      SIGNAL_BOT_NUMBER="number"
      SIGNAL_RECIPIENT_NUMBER="number"
      SALT="salt"
      EOF

    # Install MkDocs
    - pip install mkdocs mkdocs-material

    # Build MkDocs
    - mkdocs build --site-dir _readthedocs/html/

    # Build Rust Documentation
    - >
      export BINDGEN_EXTRA_CLANG_ARGS="-I$(clang -print-file-name=include) -I/usr/include/x86_64-linux-gnu -I/usr/include" &&
      cargo doc --workspace --no-deps --document-private-items

    # Output
    - mkdir -p _readthedocs/html/api
    - cp -a target/doc/. _readthedocs/html/api/
