# .readthedocs.yaml
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    rust: "1.96"

  apt_packages:
    - cmake
    - clang
    - pkg-config
    - libssl-dev
    - build-essential
    - libc6-dev
    - libclang-dev

  commands:
    - mkdir -p _readthedocs/html/

    - cargo doc --workspace --no-deps --document-private-items

    - echo '<meta http-equiv="refresh" content="0; url=prieco_core/index.html">' > target/doc/index.html

    - cp -a target/doc/. _readthedocs/html/
