[package]
name = "prieco_rs"
version = "0.1.0"
edition = "2024"

[profile.release]
#debug = true # Profiling
# Performance
opt-level = 3            # Optimization level
debug-assertions = false # Disables debug code
codegen-units = 1

# Size
strip = true
panic = "abort"
debug = 0
lto = true

[lib]
path = "src/lib.rs"

[dependencies]

# Essentials
tikv-jemallocator = "0.6.0" # Memory allocator
dotenv_codegen = "0.15.0" # .env file
num_cpus = "1.17.0" # Number of CPU cores
once_cell = "1.20.3" # Global variables
reqwest = { version = "0.12.23", features = ["json", "gzip", "brotli", "deflate"] } # Out HTTP reqvest client
rand = { version = "0.9.2", features = [
  "std",
  "std_rng",
] } # Random number generator

# Web server
rocket = { version = "0.5.1", features = ["json"] } # Web server
rocket_dyn_templates = { version = "0.1.0", features = ["handlebars"] } # Template engine
socket2 = "0.6.0" # Sockets (Run old and new instance on same port for smooth update)
tokio = { version = "1.37.0", features = ["full"] }
serde = "1.0.219"
serde_json = "1.0.142"

# Database
manticoresearch = "1.1.0"
http-body-util = "0.1.3"
redb = "3.0.1"            # Key-Value

# Vector embedding
ort = "1.16.3"
tokenizers = "0.21.1"
ndarray = "0.15.1"


# Tools
ahash = "0.8.12"      # Ultra fast single threaded hashmap
twox-hash = "2.1.2" # Predictable hash
url = "2.5.2"         # URL manager
urlencoding = "2.1.3"
brotli = "8.0.2"
mime_guess = "2.0.5"
chrono = "0.4.41" # Datetime
image = "0.25.8" # Image manipulation
