services:
  prieco:
    build:
      context: .
      dockerfile: Dockerfile
    image: prieco:latest
    ports:
      - "8000:8000"
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - tantivy:/app/data/tantivy
      - blobs:/app/data/blobs
      - meta:/app/data/meta
      - vectors:/app/data/vectors
      - ./models:/app/models:ro,z
      - ./GeoLite2-Country.mmdb:/app/GeoLite2-Country.mmdb:ro,z
    environment:
      - PRIECO_IP=0.0.0.0
      - PRIECO_PORT=8000
      - PRIECO_TANTIVY=data/tantivy
      - PRIECO_META=data/meta
      - PRIECO_VECTOR=data/vectors
      - PRIECO_BLOB=data/blobs
      - PRIECO_ID=123
      - PRIECO_WORKERS=0
    labels:
      # Podman auto-update
      - "io.containers.autoupdate=registry"
      # Watchtower track
      - "com.centurylinklabs.watchtower.enable=true"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    tty: true
    restart: unless-stopped

volumes:
  tantivy:
  blobs:
  meta:
  vectors:
