[package]
name = "prieco_pagerank"
version = "3.0.0"
authors = ["Roman Láncoš <support@prieco.net>"]
edition = "2024"

readme = "README.md"
license-file = "LICENSE"

repository = "https://codeberg.org/JojoYou/PriEco"
homepage = "https://prieco.net"

[dependencies]
prieco_core = { workspace = true }
memmap2 = "0.9.10"
zstd = { workspace = true }

[features]
cuda = []
