[package]
name = "prieco_blob"
version = "3.0.0"
authors = ["Roman Láncoš <support@prieco.net>"]
edition = "2024"

readme = "README.md"
license-file = "LICENSE"

repository = "https://codeberg.org/JojoYou/PriEco"
homepage = "https://prieco.net"

[dependencies]
prieco_core = { workspace = true }
rocksdb = { workspace = true }
zstd = { workspace = true }
fjall = { workspace = true }
tantivy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode-next = { workspace = true }
ahash = { workspace = true }
once_cell = { workspace = true }

flate2 = "1.1.9"
tar = "0.4.44"
