[package]
name = "prieco_core"
version = "3.0.0"
authors = ["Roman Láncoš <support@prieco.net>"]
edition = "2024"

readme = "README.md"
license-file = "LICENSE"

repository = "https://codeberg.org/JojoYou/PriEco"
homepage = "https://prieco.net"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
twox-hash = { workspace = true }
ahash = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }

redb = { workspace = true }
rocksdb = { workspace = true }
tantivy = { workspace = true }
tokenizers = { workspace = true }
rayon = { workspace = true }
dashmap = { workspace = true }
zstd = { workspace = true }
bytemuck = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
ndarray = { workspace = true }
rocket = { workspace = true }
memmap2 = { workspace = true }
reqwest = { workspace = true }
symspell = { workspace = true }
fjall = { workspace = true }
charabia = { workspace = true }
aho-corasick = { workspace = true }
fst = { workspace = true }
bincode-next = { workspace = true }
rkyv = { workspace = true }

[features]
default = []
cuda = ["dep:cudarc"]

[target.'cfg(target_arch = "x86_64")'.dependencies]
ort = { workspace = true, features = ["cuda", "load-dynamic"] }
cudarc = { workspace = true, optional = true, features = ["cublas", "nvrtc", "cuda-version-from-build-system"] }

[target.'cfg(not(target_arch = "x86_64"))'.dependencies]
ort = { workspace = true, features = ["load-dynamic"] }
