[package]
name = "prieco_core"
version = "3.0.0"
authors = ["Roman Láncoš <support@prieco.net>"]
edition = "2024"

readme = "README.md"
license-file = "LICENSE"

repository = "https://codeberg.org/JojoYou/PriEco"
homepage = "https://prieco.net"

[dependencies]
# Inherit from workspace
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
twox-hash = { workspace = true }
ahash = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }

# globals.rs requires these:
redb = { workspace = true }
rocksdb = { workspace = true }
tantivy = { workspace = true }
tokenizers = { workspace = true }
rayon = { workspace = true }
dashmap = { workspace = true }
zstd = { workspace = true }
bytemuck = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true }
rocket = { workspace = true}
cudarc = { workspace = true, optional = true }
memmap2 = { workspace = true }

[features]
default = []
cuda = ["dep:cudarc"]
