[package]
name = "prieco_insert"
version = "3.0.0"
authors = ["Roman Láncoš <support@prieco.net>"]
edition = "2024"

readme = "README.md"
license-file = "LICENSE"

repository = "https://codeberg.org/JojoYou/PriEco"
homepage = "https://prieco.net"

[dependencies]
prieco_core = { workspace = true }

ahash = { workspace = true }
rayon = { workspace = true }
rocksdb = { workspace = true }
tantivy = { workspace = true }
zip = { workspace = true }
zstd = { workspace = true }
serde_json = { workspace = true }
bytemuck = { workspace = true }
tokio = {workspace =true}
fjall = { workspace = true }

[features]
default = []
cuda = ["prieco_core/cuda"]
